### PR TITLE
Fix dis grids

### PR DESCRIPTION
**Pull request by andreab1997**
These are the new grids fixed after
- the [y bug](https://github.com/NNPDF/yadism/pull/196) in `yadism` was solved (which was affecting the [pinecards](https://github.com/NNPDF/pinecards/pull/171) of `HERA_CHARM` and `HERA_BOTTOM` ). 
- the [threshold bug](https://github.com/NNPDF/yadism/pull/177) solved after `yadism==0.12.3` (used version for previous grids)

This is the reason why all the DIS grids are changed. 

CC: @giacomomagni @niclaurenti

### CODE REVIEW

**Comment by AleCandido** [comment]
Why all the grids are changing, and not only HERA flavored?

**Comment by felixhekhorn** [comment]
Why did you change all of them? I guess you wanted also https://github.com/NNPDF/yadism/pull/177 in?

**Comment by felixhekhorn** [comment]
Actually, looking at the discussion there: we were available of the problem ... in the end @andreab1997 did you recompute the grids?

**Comment by andreab1997** [comment]
> Actually, looking at the discussion there: we were aware of the problem ... in the end @andreab1997 did you recompute the grids?

Judging from the results I would say no, I did not recompute them.

**Comment by felixhekhorn** [comment]
Can you please add the comparison to old? (so [this script](https://github.com/NNPDF/theories/blob/main/misc/400/nnpdf_comparison.py) I guess)

**Comment by andreab1997** [comment]
> Can you please add the comparison to old? (so [this script](https://github.com/NNPDF/theories/blob/main/misc/400/nnpdf_comparison.py) I guess)

I added the full comparison of all the sv fktables in [b7b797a](https://github.com/NNPDF/theories/pull/12/commits/b7b797ae8f4e97ccebcbabcc7e07188bb572dcb8) (for NLO) and in [d897e84](https://github.com/NNPDF/theories/pull/12/commits/d897e8484f8f4aac599698b3d4ede168db585f4c) (for NNLO)

**Comment by AleCandido** [comment]
Files are exponentially increasing, now we have 1.3k.

Are we really supposed to review? What is the use case for so many files?

**Comment by felixhekhorn** [comment]
> They are there for reference since we never had such comparisons for scale variations. You can just ignore them if you don't care but @felixhekhorn was explicitly asking for (some) of them so I guess at least him would be interested.

I think they are useful if we want to check a specific dataset and see the difference to old ...

I did look at some (not all - that is impossible) - e.g. I think these are useful:
- NNLO central:
  - charm: https://github.com/NNPDF/theories/blob/d897e8484f8f4aac599698b3d4ede168db585f4c/misc/4001/comparisons_sv/comp_424/HERACOMB_SIGMARED_C.csv up to %
  - other: https://github.com/NNPDF/theories/blob/d897e8484f8f4aac599698b3d4ede168db585f4c/misc/4001/comparisons_sv/comp_424/HERACOMBNCEP920.csv no visible change
- NNLO SV:
  - charm https://github.com/NNPDF/theories/blob/d897e8484f8f4aac599698b3d4ede168db585f4c/misc/4001/comparisons_sv/comp_420/HERACOMB_SIGMARED_C.csv up to 20% and even more
  - other: https://github.com/NNPDF/theories/blob/fix_DIS_grids/misc/4001/comparisons_sv/comp_420/HERACOMBNCEP920.csv up to few percent and sometimes more
- NLO central:
  - charm: https://github.com/NNPDF/theories/blob/d897e8484f8f4aac599698b3d4ede168db585f4c/misc/4005/comparisons_sv/comp_405/HERACOMB_SIGMARED_C.csv same: up to %
  - other: https://github.com/NNPDF/theories/blob/d897e8484f8f4aac599698b3d4ede168db585f4c/misc/4005/comparisons_sv/comp_405/HERACOMBNCEP920.csv same: not visible
- NLO SV: 
  - charm https://github.com/NNPDF/theories/blob/d897e8484f8f4aac599698b3d4ede168db585f4c/misc/4005/comparisons_sv/comp_401/HERACOMB_SIGMARED_C.csv yet bigger impact (including change of sign and order of magnitude)
  - other: https://github.com/NNPDF/theories/blob/d897e8484f8f4aac599698b3d4ede168db585f4c/misc/4005/comparisons_sv/comp_401/HERACOMBNCEP920.csv similarly: significantly bigger impact than NNLO

(I hope, I correctly identified the central)

arguably you can drop all the non-DIS stuff - they are useless here (`rm -rf data/400{1,5}/*/*/{ATLAS,CMS}*` or something similar might work)

**Comment by andreab1997** [comment]
Can we merge this?

**Comment by felixhekhorn** [comment]
> arguably you can drop all the non-DIS stuff - they are useless here (`rm -rf misc/400{1,5}/*/*/{ATLAS,CMS}*` or something similar might work)

I would still do this before - but can even be skipped if you wish ...

what is theory 4005? (400 = NNLO & 405 = NLO, right?)

**Comment by andreab1997** [comment]
> > arguably you can drop all the non-DIS stuff - they are useless here (`rm -rf misc/400{1,5}/*/*/{ATLAS,CMS}*` or something similar might work)
> 
> I would still do this before - but can even be skipped if you wish ...
> 
> what is theory 4005? (400 = NNLO & 405 = NLO, right?)

Yes 4005 is NLO but it does not contain the original grids. It contains the grid with the ren_sv order included by `pineko`

**Comment by andreab1997** [comment]
> > arguably you can drop all the non-DIS stuff - they are useless here (`rm -rf misc/400{1,5}/*/*/{ATLAS,CMS}*` or something similar might work)
> 
> I would still do this before - but can even be skipped if you wish ...
> 
> what is theory 4005? (400 = NNLO & 405 = NLO, right?)

Actually I would keep also the hadronic: so far we did not have anything to compare with for scale variations. At least, next time we will need to update the grids, we will something to compare to.

**Review by felixhekhorn — APPROVED** [review]

**Pull request merged**
